[tool.ruff]
line-length = 119
src = ["src"]
exclude = [
    "migrations"
]
target-version = "py311"

[tool.ruff.lint]
fixable = ["ALL"]
select = ["E", "W", "F", "I", "B", "C4", "UP", "N", "A", "COM", "C4", "DJ", "PIE", "T20", "Q", "RSE",
"RET", "SIM", "PL", "RUF"]
#"E": Ошибки синтаксиса и логики, обнаруживаемые инструментом Pyflakes.
#"W": Предупреждения, обнаруживаемые инструментом Pyflakes.
#"F": Ошибки форматирования кода, такие как несоответствие PEP 8.
#"I": Указание на неправильно расставленные импорты.
#"B": Правила из пакета Bugbear, которые помогают выявлять потенциальные ошибки в коде.
#"C4": Правила из пакета flake8-comprehensions, которые нацелены на улучшение производительности и читаемости кода.
#"UP": Правила из пакета flake8-use-pathlib, которые помогают использовать pathlib вместо устаревших методов работы с файлами.
#"N": Правила из пакета flake8-bugbear, нацеленные на снижение вероятности ошибок.
#"A": Правила из пакета flake8-annotations, которые проверяют аннотации типов.
#"COM": Правила для комментариев.
#"DJ": Правила, специфичные для проектов на Django.
#"PIE": Правила из пакета flake8-pie, которые улучшают читаемость и надежность кода.
#"T20": Правила для форматирования строк.
#"Q": Правила из пакета flake8-quotes, которые проверяют использование кавычек.
#"RSE": Правила для стиля кода, особенно полезны в научных вычислениях.
#"RET": Правила, касающиеся обработки возвратов в функциях.
#"SIM": Правила для упрощения кода.
#"PL": Правила из пакета pylint.
#"RUF": Внутренние правила Ruff

ignore = ["RUF012", "RUF001", "RUF002", "RUF003", "PLR0911", "PLR0912"]


[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"