# Generated by Django 5.2.3 on 2025-06-24 21:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        help_text="Enter the name of the category",
                        max_length=255,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        null=True,
                        verbose_name="Category Description",
                    ),
                ),
                (
                    "category_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the category",
                        null=True,
                        verbose_name="Category Settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Enter the name of the file",
                        max_length=255,
                        unique=True,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the file",
                        null=True,
                        verbose_name="File Description",
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        help_text="Upload the document file",
                        upload_to="uploads/files/",
                        verbose_name="File Upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_title",
                    models.CharField(
                        help_text="Enter the title or name of the link",
                        max_length=255,
                        unique=True,
                        verbose_name="Link Title",
                    ),
                ),
                (
                    "link_description",
                    models.TextField(
                        blank=True,
                        help_text="Description or notes about the link",
                        null=True,
                        verbose_name="Link Description",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        help_text="URL address of the material",
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Enter the name of the location",
                        max_length=255,
                        unique=True,
                        verbose_name="Location Name",
                    ),
                ),
                (
                    "location_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the location",
                        null=True,
                        verbose_name="Location Description",
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True,
                        help_text="Physical address of the location",
                        max_length=512,
                        null=True,
                        verbose_name="Location Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        help_text="Enter the name of the task status",
                        max_length=100,
                        unique=True,
                        verbose_name="Status Name",
                    ),
                ),
                (
                    "status_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the status",
                        null=True,
                        verbose_name="Status Description",
                    ),
                ),
                (
                    "status_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the status",
                        null=True,
                        verbose_name="Status Settings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the category",
                        max_length=255,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category",
                        null=True,
                        verbose_name="Category Description",
                    ),
                ),
                (
                    "category_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the category",
                        null=True,
                        verbose_name="Category Settings",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categorys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the file",
                        max_length=255,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the file",
                        null=True,
                        verbose_name="File Description",
                    ),
                ),
                (
                    "file_upload",
                    models.TextField(
                        help_text="Upload the document file",
                        max_length=100,
                        verbose_name="File Upload",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical file",
                "verbose_name_plural": "historical files",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLink",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "link_title",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the title or name of the link",
                        max_length=255,
                        verbose_name="Link Title",
                    ),
                ),
                (
                    "link_description",
                    models.TextField(
                        blank=True,
                        help_text="Description or notes about the link",
                        null=True,
                        verbose_name="Link Description",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        db_index=True,
                        help_text="URL address of the material",
                        verbose_name="URL",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical link",
                "verbose_name_plural": "historical links",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the location",
                        max_length=255,
                        verbose_name="Location Name",
                    ),
                ),
                (
                    "location_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the location",
                        null=True,
                        verbose_name="Location Description",
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True,
                        help_text="Physical address of the location",
                        max_length=512,
                        null=True,
                        verbose_name="Location Address",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSpace",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "space_name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the space",
                        max_length=255,
                        verbose_name="Space Name",
                    ),
                ),
                (
                    "space_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the space",
                        null=True,
                        verbose_name="Space Settings",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="The date and time when the space was created",
                        verbose_name="Created At",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical space",
                "verbose_name_plural": "historical spaces",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStatus",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter the name of the task status",
                        max_length=100,
                        verbose_name="Status Name",
                    ),
                ),
                (
                    "status_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the status",
                        null=True,
                        verbose_name="Status Description",
                    ),
                ),
                (
                    "status_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the status",
                        null=True,
                        verbose_name="Status Settings",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical status",
                "verbose_name_plural": "historical statuss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space_name",
                    models.CharField(
                        help_text="Enter the name of the space",
                        max_length=255,
                        unique=True,
                        verbose_name="Space Name",
                    ),
                ),
                (
                    "space_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the space",
                        null=True,
                        verbose_name="Space Settings",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the space was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "space_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who belong to this space",
                        related_name="spaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Space Users",
                    ),
                ),
            ],
        ),
    ]
