# Generated by Django 5.2.3 on 2025-06-26 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = []
