FROM python:3.11

WORKDIR /task_manager

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client

COPY ./utils/wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

COPY . .