name: Run Django Tests
on: [push]

jobs:
  #test-django-app:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      python-version: ["3.11"]
  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 0
  #    - name: Set up Python ${{ matrix.python-version }}
  #      uses: actions/setup-python@v3
  #      with:
  #        python-version: ${{ matrix.python-version }}
  #    - name: Install dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #    - name: Run Django test
  #      run: |
  #        python manage.py test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'


      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff
        run: ruff check --fix

  check_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools
    - name: Check for outdated dependencies
      run: |
        pip list --outdated --format=columns || echo "No outdated packages found"
    - name: Check for security vulnerabilities
      run: |
        pip install pip-audit
        pip-audit || echo "Vulnerabilities found (see report above)"
    - name: Fail if setuptools is vulnerable
      run: |
        pip list | grep setuptools
        if pip list | grep 'setuptools\s*65\.5\.0'; then
          echo "::error::Vulnerable setuptools version detected (65.5.0). Please upgrade to 65.5.1 or higher."
          exit 1
        fi
  
  check_migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check for new migrations
      run: |
        python manage.py makemigrations --dry-run --check || (echo "Error: New migrations detected. Please run 'makemigrations' and commit them." && exit 1)
    - name: Check migration conflicts
      run: |
        python manage.py makemigrations --check --dry-run || (echo "Error: Migration conflicts detected. Please resolve them." && exit 1)